### PR TITLE
Upgrades Slap to 1.7.2

### PR DESCRIPTION
**Pull request by Tpt**

### CODE REVIEW

**Comment by NiklasRosenstein** [comment]
Thanks @Tpt.

I'm not sure why there's an issue with installing nodejs in the Bionic image now though.

**Comment by cdbrkfxrpt** [comment]
the issue is that apparently the latest nodejs requires a libc at >= 2.28 but [Ubuntu Bionic / 18.04 has 2.27 in its packages](https://packages.ubuntu.com/bionic/libc-bin):

```
[2229](https://github.com/kraken-build/kraken-base-image/actions/runs/4231882504/jobs/7350942308#step:10:2230)
Tue, 21 Feb 2023 10:56:36 GMT #15 23.58 nodejs : Depends: libc6 (>= 2.28) but 2.27-3ubuntu1.6 is to be installed
[2230](https://github.com/kraken-build/kraken-base-image/actions/runs/4231882504/jobs/7350942308#step:10:2231)
Tue, 21 Feb 2023 10:56:36 GMT #15 23.60 E: Unable to correct problems, you have held broken packages.
```

so either hold nodejs on 18.04 or drop 18.04

**Comment by NiklasRosenstein** [comment]
@cdbrkfxrpt We build some Rust projects with 18.04 because of the Glibc version so they can run directly on Jetsons with 18.04. So I don't think we can phase out 18.04.

**Comment by Tpt** [comment]
@NiklasRosenstein cargo-zigbuild allows to (cross-)compile to older glibc: https://github.com/rust-cross/cargo-zigbuild
It might be interesting to experiment with it.

**Comment by cdbrkfxrpt** [comment]
the chosen solution is to hold nodejs on version 16, which has no issues with the libc packaged in ubuntu 18.04, for the 18.04 image, and only use nodejs 18 on the newer ubuntu versions.

this has been implemented and merged in #28

**Review by cdbrkfxrpt — APPROVED** [review]
LGTM

**Pull request merged**
