### PR TITLE
Update Dockerfile: Bump Rust version to 1.77.0

### PR DESCRIPTION
**Pull request by wngr**

### CODE REVIEW

**Review by Tpt — APPROVED** [review]

**Comment by NiklasRosenstein** [comment]
IRC the reason we didn't upgrade was because we don't run `cargo login` in Kraken yet, and that is still not quite the case

**Comment by wngr** [comment]
Hm. What's the concern; is there an ongoing effort?

We should strive to keep up to date with latest stable.

**Comment by Tpt** [comment]
@NiklasRosenstein I am confused, weren't the `cargo login` changes shipped with Rust 1.74?

**Comment by NiklasRosenstein** [comment]
Actually yes, it works because we temporarily inject auth tokens into the config.

https://github.com/kraken-build/kraken/blob/16c67f4c758db4b759c786671892b953a58d0876/kraken-build/src/kraken/std/cargo/tasks/cargo_auth_proxy_task.py#L71

**Comment by NiklasRosenstein** [comment]
Can you please update the `README.md` as well with the Rust version we're using now?

**Pull request merged**
